# Generated by Django 5.2.10 on 2026-01-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0)),
                ('category_weights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_queries', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('gathering', 'Gathering Responses'), ('voting', 'Voting'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('council_mode', models.CharField(choices=[('ranked', 'Ranked Voting'), ('majority', 'Majority Vote'), ('synthesis', 'Synthesis'), ('debate', 'Debate')], default='ranked', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('queries', models.ManyToManyField(blank=True, related_name='tags', to='council_app.query')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('label', models.CharField(max_length=1)),
                ('response_time', models.FloatField(default=0.0)),
                ('is_winner', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='council_app.modelconfig')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='council_app.query')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('query', 'label')},
            },
        ),
        migrations.AddField(
            model_name='query',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_queries', to='council_app.response'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.JSONField()),
                ('raw_response', models.TextField(blank=True)),
                ('voted_on_models', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='council_app.query')),
                ('voter_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='council_app.modelconfig')),
            ],
            options={
                'unique_together': {('query', 'voter_model')},
            },
        ),
    ]
