# Generated by Django 5.2.10 on 2026-01-31 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('page', 'Page of Writing'), ('outline', 'Outline'), ('story', 'Story'), ('essay', 'Essay'), ('poetry', 'Poetry')], default='page', max_length=20)),
                ('processing_mode', models.CharField(choices=[('manual', 'Manual (trigger each iteration)'), ('auto_batch', 'Automatic Batch')], default='manual', max_length=20)),
                ('default_churn_type', models.CharField(choices=[('edit', 'Edit & Refine'), ('expand', 'Expand Outline'), ('explore', 'Explore Variations')], default='edit', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_models', models.ManyToManyField(blank=True, related_name='churn_projects', to='council_app.modelconfig')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurnIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('iteration_number', models.PositiveIntegerField(default=1)),
                ('content', models.TextField()),
                ('content_diff', models.TextField(blank=True)),
                ('churn_type', models.CharField(choices=[('edit', 'Edit & Refine'), ('expand', 'Expand Outline'), ('explore', 'Explore Variations')], default='edit', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('archived', 'Archived'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('models_used', models.ManyToManyField(blank=True, related_name='churn_iterations', to='council_app.modelconfig')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='council_app.churniteration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='council_app.creativeproject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IterationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synthesized_feedback', models.TextField()),
                ('suggested_content', models.TextField(blank=True)),
                ('raw_responses', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iteration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='council_app.churniteration')),
            ],
        ),
    ]
