# Generated by Django 5.2.10 on 2026-02-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_app', '0002_creativeproject_churniteration_iterationfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, help_text='Timeout in seconds (uses global default if blank)', null=True),
        ),
    ]
