# Generated by Django 5.2.10 on 2026-02-06 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_app', '0003_add_model_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Query Started'), ('querying', 'Querying Model'), ('success', 'Model Responded'), ('error', 'Model Error'), ('timeout', 'Model Timeout'), ('retry', 'Retrying Model'), ('voting_start', 'Voting Started'), ('voting', 'Model Voting'), ('voted', 'Model Voted'), ('complete', 'Query Complete'), ('query_error', 'Query Error')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='council_app.query')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
