# Generated by Django 5.2.10 on 2026-02-06 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_app', '0004_add_query_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Knowledge content in markdown format (style guides, templates, requirements)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Knowledge Base',
                'verbose_name_plural': 'Report Knowledge Bases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='churniteration',
            name='churn_type',
            field=models.CharField(choices=[('edit', 'Edit & Refine'), ('expand', 'Expand Outline'), ('explore', 'Explore Variations'), ('report', 'Report Review')], default='edit', max_length=20),
        ),
        migrations.AlterField(
            model_name='creativeproject',
            name='content_type',
            field=models.CharField(choices=[('page', 'Page of Writing'), ('outline', 'Outline'), ('story', 'Story'), ('essay', 'Essay'), ('poetry', 'Poetry'), ('report', 'Technical Report')], default='page', max_length=20),
        ),
        migrations.AlterField(
            model_name='creativeproject',
            name='default_churn_type',
            field=models.CharField(choices=[('edit', 'Edit & Refine'), ('expand', 'Expand Outline'), ('explore', 'Explore Variations'), ('report', 'Report Review')], default='edit', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_outline', models.TextField(help_text='Original outline as submitted (markdown)')),
                ('parsed_sections', models.JSONField(default=list, help_text='Parsed sections: [{id, title, content, level, parent_id, order}]')),
                ('report_type', models.CharField(choices=[('technical', 'Technical Report'), ('research', 'Research Paper'), ('proposal', 'Proposal')], default='technical', max_length=20)),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('processing_mode', models.CharField(choices=[('sequential', 'Sequential (one at a time)'), ('parallel', 'Parallel (all at once)')], default='sequential', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledgebase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_outlines', to='council_app.reportknowledgebase')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_outline', to='council_app.creativeproject')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(help_text='References parsed_sections[].id', max_length=50)),
                ('section_title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('original_content', models.TextField(blank=True)),
                ('current_content', models.TextField(blank=True)),
                ('content_diff', models.TextField(blank=True)),
                ('knowledge_context', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('review', 'Awaiting Review'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('iteration_count', models.PositiveIntegerField(default=0)),
                ('compliance_score', models.FloatField(blank=True, help_text='Compliance score from 0.0 to 1.0', null=True)),
                ('council_feedback', models.JSONField(blank=True, default=dict, help_text='Structured feedback from latest review')),
                ('raw_responses', models.JSONField(blank=True, default=list, help_text='Individual model responses')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='council_app.reportoutline')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('report_outline', 'section_id')},
            },
        ),
    ]
