# Generated by Django 5.2.10 on 2026-02-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_app', '0005_add_report_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_validated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='response',
            name='validation_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
