# Generated by Django 5.2.10 on 2026-02-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_app', '0008_add_churn_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='churnconfig',
            name='debug_full_responses',
            field=models.BooleanField(default=False, help_text='Store full model responses in debug_info (can be large)'),
        ),
        migrations.AddField(
            model_name='churnconfig',
            name='debug_response_max_chars',
            field=models.PositiveIntegerField(default=500, help_text='Max chars per response in debug_info when debug_full_responses is False'),
        ),
        migrations.AddField(
            model_name='churniteration',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='When True, the running task will stop at the next stage boundary'),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='When True, the running task will stop at the next stage boundary'),
        ),
    ]
