# Generated by Django 5.2.10 on 2026-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_app', '0009_add_churn_debug_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection',
            name='debug_info',
            field=models.JSONField(blank=True, default=dict, help_text='Live debug info during processing (model responses, etc.)'),
        ),
    ]
