"""
Django settings for council_project project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8u28%tsgrn^*j@91ae1v@iivygi46bq1gk6qe-!d(jlqjw70e4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'django_htmx',
    'django_q',
    # Local apps
    'council_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'council_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'council_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (uploaded PDFs, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django-Q2 Configuration
Q_CLUSTER = {
    'name': 'council',
    'workers': 2,
    'recycle': 500,
    'timeout': 1800,  # 30 minutes - allows for slow LLM inference on Raspberry Pi
    'retry': 2100,    # 35 minutes - must be > timeout
    'compress': True,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 1,
    'label': 'Council Queue',
    'orm': 'default',  # Use Django ORM as broker
}

# Council Configuration
COUNCIL_CONFIG = {
    'OLLAMA_URL': 'http://localhost:11434',
    'DEFAULT_TIMEOUT': 600,  # 10 minutes - extended timeout for slow models on limited RAM systems
    'DEFAULT_RETRIES': 2,
    'EXCLUDE_SELF_VOTE': True,
    # Ollama generation options (reduce response times on limited hardware)
    'NUM_PREDICT': 4096,  # Max tokens to generate (None = unlimited)
    'KEEP_ALIVE': '5m',  # Keep model in memory between requests
    'NUM_CTX': None,  # Context window (None = use model default)
    # Churn-specific optimizations
    'CHURN_SEQUENTIAL_MODELS': True,  # Run models one at a time (better for Pi)
    'CHURN_MAX_CONTENT_CHARS': 8000,  # Max chars of user content in prompts (~2000 words)
    'CHURN_MAX_SYNTHESIS_RESPONSE_CHARS': 3000,  # Max chars per response in synthesis prompt
    'CHURN_USE_STREAMING': False,  # Stream Ollama response to avoid 5-min timeout
}

# ChromaDB Configuration (local vector database)
CHROMADB_PATH = BASE_DIR / 'chromadb_data'

# PDF Processing Configuration
PDF_PROCESSING = {
    'DEFAULT_DPI': 150,          # DPI for rendering PDF pages to images (lower = less RAM)
    'DEFAULT_VISION_MODEL': 'moondream',  # Small vision model for RPi
    'EMBEDDING_MODEL': 'nomic-embed-text',  # Embedding model for ChromaDB
    'NUM_PREDICT': 4096,         # Max tokens for vision model output per page
    'PAGE_TIMEOUT': 600,         # Timeout per page in seconds (10 min)
}


# Logging Configuration for Debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'council_debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'council_app': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'council': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
